apiVersion: v1
kind: Service
metadata:
  name: demo-helloworld
  namespace: demos
  labels:
    app: demo
    tier: backend
spec:
  type: NodePort
  selector:
    name: demo-helloworld-backend
    app: demo
    tier: backend
  ports:
  - name: http
    port: 8089
    protocol: TCP
    targetPort: 8089
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-helloworld
  namespace: demos
spec:
  selector:
    matchLabels:
      app: demo
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        name: demo-helloworld-backend
        app: demo
        tier: backend
    spec:
      containers:
      - name: helloworld-backend
    # enter the path to your image, be sure to include the correct region prefix    
        image: <your image>:latest
      imagePullSecrets:
    # enter the name of the secret you created  
      - name: <your secret>
